#!/usr/bin/env node
// Converts Danny's finalized Guide articles (content/guides/<locale>/NN-slug.md) into
// data/guide-articles.generated.ts. Article wording is copied as-is: this script only
// changes structure (headings, lists, quotes, bold), never text.
// Usage: node scripts/import-guides.mjs
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const locales = ["zh-TW", "en"];

const unescape = (text) => text.replace(/\\([\\`*_{}[\]()#+\-.!~|>])/g, "$1");
const clean = (text) => unescape(text).replace(/\s+$/u, "");
const stripBold = (text) => text.replace(/^\*\*(.*)\*\*$/u, "$1").trim();
const stripPrefix = (text) => text.replace(/^(【[^】]*】)+\s*/u, "").trim();

function parseArticle(source, locale) {
  // Chinese lines join directly; English lines need a space between them.
  const joiner = locale === "en" ? " " : "";
  const lines = source.replace(/\r\n/g, "\n").split("\n");
  const meta = {};
  let start = 0;
  if (lines[0]?.trim() === "---") {
    const end = lines.indexOf("---", 1);
    for (const line of lines.slice(1, end)) {
      const match = line.match(/^([^:]+):\s*(.*)$/u);
      if (match) meta[match[1].trim()] = match[2].trim();
    }
    start = end + 1;
  }

  const raw = [];
  let paragraph = [];
  let title = "";
  const flush = () => {
    if (paragraph.length) {
      const text = clean(paragraph.join(joiner));
      // A numbered bold heading accidentally joined to the end of a paragraph becomes its own heading.
      const joined = text.match(/^(.*[。？！?])\*\*(\d+\.\s.+)\*\*$/u);
      if (joined) raw.push({ type: "paragraph", text: joined[1] }, { type: "heading", depth: 0, text: joined[2] });
      else raw.push({ type: "paragraph", text });
    }
    paragraph = [];
  };

  for (const line of lines.slice(start)) {
    if (!line.trim()) { flush(); continue; }
    const heading = line.match(/^(#{1,6})\s+(.*)$/u);
    if (heading) {
      flush();
      const text = stripBold(clean(heading[2]));
      if (!title) { title = stripPrefix(text); continue; }
      raw.push({ type: "heading", depth: heading[1].length, text });
      continue;
    }
    const bullet = line.match(/^\s*[-*+]\s+(.*)$/u);
    const ordered = line.match(/^\s*\d+\\?\.\s+(.*)$/u);
    if (bullet || ordered) {
      flush();
      const kind = bullet ? "list" : "ordered";
      const item = clean((bullet ?? ordered)[1]).replace(/^>\s*/u, "");
      const last = raw.at(-1);
      if (last?.type === kind) last.items.push(item);
      else raw.push({ type: kind, items: [item] });
      continue;
    }
    const quote = line.match(/^>\s?(.*)$/u);
    if (quote) {
      flush();
      const last = raw.at(-1);
      if (last?.type === "quote" && last.open) last.text += clean(quote[1]);
      else raw.push({ type: "quote", text: clean(quote[1]), open: true });
      continue;
    }
    // Indented continuation of the previous list item.
    const last = raw.at(-1);
    if (/^\s{2,}/u.test(line) && !paragraph.length && (last?.type === "list" || last?.type === "ordered")) {
      last.items[last.items.length - 1] += joiner + clean(line.trim());
      continue;
    }
    paragraph.push(line.trim());
  }
  flush();

  // The most common heading depth becomes <h2>; deeper headings become <h3>.
  const depths = raw.filter((block) => block.type === "heading" && block.depth > 0).map((block) => block.depth);
  const counts = new Map();
  for (const depth of depths) counts.set(depth, (counts.get(depth) ?? 0) + 1);
  const main = [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0] - b[0])[0]?.[0] ?? 2;

  let index = 0;
  const body = raw.map((block) => {
    if (block.type === "heading") return { type: "heading", id: `section-${++index}`, text: block.text, level: block.depth > main ? 3 : 2 };

    if (block.type === "ordered") return { type: "list", ordered: true, items: block.items };
    if (block.type === "quote") return { type: "quote", text: block.text };
    return block;
  });

  return { meta, title, body };
}

const output = {};
for (const locale of locales) {
  const dir = join(root, "content/guides", locale);
  for (const file of readdirSync(dir).filter((name) => name.endsWith(".md")).sort()) {
    const slug = file.replace(/^\d+-/u, "").replace(/\.md$/u, "");
    const { meta, title, body } = parseArticle(readFileSync(join(dir, file), "utf8"), locale);
    output[`${locale}/${slug}`] = { number: Number(meta["篇號"]) || null, sourceStatus: meta["狀態"] ?? null, title, body };
  }
}

const banner = "// Generated by scripts/import-guides.mjs from content/guides. Do not edit by hand.\n";
const file = `${banner}import type { GuideBodyBlock } from "@/lib/content/types";\n\nexport type ImportedArticle = { number: number | null; sourceStatus: string | null; title: string; body: GuideBodyBlock[] };\n\nexport const importedArticles: Record<string, ImportedArticle> = ${JSON.stringify(output, null, 2)};\n`;
writeFileSync(join(root, "data/guide-articles.generated.ts"), file);
console.log(`Imported ${Object.keys(output).length} articles.`);
